OpenAI_key = "0ex1PzLjNNRdvH68xj5qaJrwWXgUgI2op3znzIkFfZ97ZXbzCSUomxp2cKr3bnI_iYfYHdvjWvT3BlbkFJq4Te1bDZqFaB137xoxQSdB7w5Jl6XrPCRRZXPFfENjOyoU5w4fmzuHUUeiugajFr3F8P_AqNIA"
#whitelist = ["sally", "bob", "joe"]

[database]
#user = "your username"
#password = "your password"
